# Generated by Django 4.2.16 on 2026-03-01 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée stock'), ('sortie', 'Sortie stock'), ('ajustement', 'Ajustement')], max_length=20)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_avant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_apres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motif', models.CharField(blank=True, max_length=255, null=True)),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='produits.produit')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mouvement Stock',
                'verbose_name_plural': 'Mouvements Stock',
                'ordering': ['-date_mouvement'],
            },
        ),
    ]
